Hepsi: derle bagla calistir

derle:
	g++ -I"./include" -c ./src/main.cpp -o ./lib/main.o
	g++ -I"./include" -c ./src/BST.cpp -o ./lib/BST.o
	g++ -I"./include" -c ./src/Hexagon.cpp -o ./lib/Hexagon.o
	g++ -I"./include" -c ./src/Manager.cpp -o ./lib/Manager.o
	g++ -I"./include" -c ./src/Node.cpp -o ./lib/Node.o
bagla:
	g++ ./lib/main.o ./lib/BST.o ./lib/Hexagon.o ./lib/Manager.o ./lib/Node.o -o ./bin/program

calistir:
	./bin/program